### ISSUE TITLE
relationship of the arguments right and balance.

### ISSUE THREAD

**Issue by lorenzwalthert** [jonmcalder/refactor#2]
## Problem

If `length(breaks) == 1`, the option `right` remains without effect, whereas in the case of `length(breaks) > 1`, the option `balance` remains without effect but no message is issued.
## Suggested solution

Since both options refer to more or less the same (if not exactly the same), we should only keep one.

**Comment by jonmcalder** [comment]
Intuitively I utilised separate parameters since they are applied in
different contexts but I agree that this is probably not necessary. Let's
keep the 'right' argument, and update code functionality and documentation
to reflect the different ways the parameter can be 'interpreted' for each
context.
